### PR TITLE
Fix Streak syncing errors

### LINKED ISSUE #27: NoMethodError: undefined method `leaders' for nil:NilClass
https://sentry.io/hack-club/api/issues/200755855/

```
NoMethodError: undefined method `leaders' for nil:NilClass
  app/jobs/update_from_streak_job.rb:88:in `block (4 levels) in perform'
    instance.send(association.plural_name) << instance_to_associate
  app/jobs/update_from_streak_job.rb:64:in `each'
    model.streakable_associations.each do |association|
  app/jobs/update_from_streak_job.rb:64:in `block (3 levels) in perform'
    model.streakable_associations.each do |association|
  app/jobs/update_from_streak_job.rb:63:in `each'
    linked_box_keys.each do |linked_box_key|
  app/jobs/update_from_streak_job.rb:63:in `block (2 levels) in perform'
    linked_box_keys.each do |linked_box_key|
...
(134 additional frame(s) were not displayed)

NoMethodError: undefined method `leaders' for nil:NilClass
```

### PR DESCRIPTION
**Pull request by zachlatta**
This pull request makes a few changes to how Streak syncing is handled to fix a few edge cases.

- If the creation of a new record in the DB fails during syncing, an exception is now thrown (previously, it was ignored)
  - This closes #27 
- Remove duplicate club <-> leader relationships and prevent future ones from being created (previously, a club could have an associate with the same leader twice – or vice versa)
- If a Streakable model is created with a `streak_key`, don't skip sending updates back to Streak when saving
  - This handles the case where a Club is created with `streak_key`, `name`, and `address` set, but missing `latitude` and `longitude`. Previously the `address` would be geocoded and `latitude` and `longitude` would be set, but the new `latitude` and `longitude` wouldn't be sent to Streak (as long as the model was just being created, it'd send updates if the address later changes in an existing record)

### CODE REVIEW

File: spec/support/shared_examples/streakable.rb [hunk 1]
```diff
@@ -48,6 +48,34 @@
...
+      let(:box_client) { class_double(StreakClient::Box).as_stubbed_const }
+
+      it "doesn't create another box, but does send updates" do
+        expect(box_client).to_not receive(:create_in_pipeline)
+
+        expect_update_box(
+          streak_client_double: box_client,
+          streak_key: attrs[model.key_attribute],
+          notes: attrs[model.notes_attribute],
+          linked_box_keys: [] # TODO: Don't do this
```
Comment (paked) [inline spec/support/shared_examples/streakable.rb]: You've left a todo here. Would you mind either expanding on what it is or straight up addressing it?

**Review by paked — CHANGES_REQUESTED** [review]
